# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/credito_sicredi}

# Hibernate
quarkus.hibernate-orm.database.generation=update

# REST Client - Produto Credito
quarkus.rest-client."br.com.sicredi.credito.client.ProdutoCreditoClient".url=https://desafio-creditosicredi.wiremockapi.cloud
quarkus.rest-client."br.com.sicredi.credito.client.ProdutoCreditoClient".connect-timeout=5000
quarkus.rest-client."br.com.sicredi.credito.client.ProdutoCreditoClient".read-timeout=5000
